### ISSUE TITLE
Newly trained model is not answering with the correct data in response to questions

### ISSUE THREAD

**Issue by stevef1uk** [instructlab/instructlab#1319]
**Describe the bug**
I have followed the instructions for using ilab on my Mac M2 Pro 16GB machine (Sonoma 14.5) and when running lab chat trained model with the sample Oscars text I am getting the wrong responses! I want to say that is great one can now do the LLM fine-tuning so easily on a Mac :-) , however, adding facts needs to return the right data. This was a clean git pull so starting from the default position.

**To Reproduce**
Follow the tutorial and add the Oscars data as per the tutorial.

**Expected behavior**
When running ' ilab serve --model-path instructlab-merlinite-7b-lab-trained/instructlab-merlinite-7b-lab-Q4_K_M.gguf' & on another window Ilab chat I was expecting to see answers matching the training data and I don't get that

**Screenshots**
<img width="1009" alt="Screenshot 2024-06-10 at 18 49 40" src="https://github.com/instructlab/instructlab/assets/843865/79f7b33a-bce2-4aa0-8317-4b5a74e86e12">
<img width="1101" alt="Screenshot 2024-06-10 at 18 58 38" src="https://github.com/instructlab/instructlab/assets/843865/3ba86bad-33b8-42c7-9c4d-c9b469fc0906">
<img width="1320" alt="Screenshot 2024-06-10 at 19 01 11" src="https://github.com/instructlab/instructlab/assets/843865/e155968f-c65d-47d6-8d8f-d9d6e21cf553">
<img width="544" alt="Screenshot 2024-06-10 at 19 30 03" src="https://github.com/instructlab/instructlab/assets/843865/9331a184-59eb-4834-ae75-8dc6f55da973">

**Device Info (please complete the following information):**
 - Hardware Specs: Mac mini Apple M2 Pro Chip, 16 GB Memory
 - OS Version: Sonoma 14.5
 - Python Version: Python 3.11.5
 - InstructLab Version:  0.16.1

Training data:
```
version: 2
task_description: 'Teach the model the results of the 2024 Oscars'
created_by: juliadenham
domain: pop_culture
seed_examples:
 - question: When did the 2024 Oscars happen?
   answer: |
     The 2024 Oscars were held on March 10, 2024.
 - question: What film had the most Oscar nominations in 2024?
   answer: |
     Oppenheimer had 13 Oscar nominations.
 - question: Who presented the 2024 Oscar for Best Original Screenplay and Best Adapted Screenplay?
   answer: |
     Octavia Spencer presented the award for Best Original Screenplay and Best Adapted Screenplay at the 2024 Oscars.
 - question: Who hosted the 2024 Oscars?
   answer: |
     Jimmy Kimmel hosted the 96th Academy Awards ceremony.
 - question: At the 2024 Oscars, who were the nominees for best director and who won?
   answer: |
     The nominees for director at the 2024 Oscars was Christopher Nolan for Oppenheimer,
     Justine Triet for Anatomy of a Fall, Martin Scorsese for Killers of the Flower Moon,
     Yorgos Lanthimos for Poor Things, and Jonathan Glazer for The Zone of Interest.
     Christopher Nolan won best director for Oppenheimer.
 - question: Did Billie Eilish perform at the 2024 Oscars?
   answer: |
     Yes Billie Eilish performed "What Was I Made For?" from Barbie at the 2024 Oscars.
document:
 repo: https://github.com/juliadenham/oscars2024_knowledge.git
 commit: e1744af
 patterns:
  - oscars2024_results.md
```

**Comment by cmar28** [comment]
I am having the same issue (Mac M1 Max 32G) fine tuning on the same use case. Ilab 0.16.1 Answers of the model on the domain it was supposed to be trained on are worse than the base model

![Screenshot 2024-06-10 at 20 12 54](https://github.com/instructlab/instructlab/assets/16029766/16ce4e69-ee41-4740-b88d-eea778c3be00)
![Screenshot 2024-06-10 at 20 12 45](https://github.com/instructlab/instructlab/assets/16029766/effc29f8-07e7-4c41-bbc1-6f91f19de20b)

**Comment by stevef1uk** [comment]
Glad is wasn't just me. I watched the RedHat vide announcing this and they mentioned that synthetic data was generated from the data entered by customers was used to train the model. Perhaps that incorrect data is what is being used by the model?

**Comment by chudegao** [comment]
Can you share the data you generated?  In ./generated or ./taxonomy_data directory.
What's the command parameter you used for generate data and model training?

**Comment by stevef1uk** [comment]
> Can you share the data you generated? In ./generated or ./taxonomy_data directory. What's the command parameter you used for generate data and model training?

I followed the instruction here: https://github.com/instructlab/taxonomy/blob/main/README.md so my original data file I added to the taxonomy was as I have shown above. Then I followed the instructions to run:
```
ilab diff.  - to check my data was valid. I needed to fix an indentation on the final line I seem to remember
ilab generate
ilab train
ilab test
ilab convert

I looked in the taxonomy_data directory and I can see lots of generated data for try Oscars 2024, however, generally even if I enter that training data into the chat dialogue it doesn't give those results either.

e.g. taking a line from train.json in that directory:

'"Who was nominated for Best Actor but did not win at the Oscars this year?", "assistant": "The nominees for Best Actor who did not win include:\n1. Adam Driver (The Zone of Interest)\n2. Antonio Banderas (Barbie)\n3. Austin Butler (Oppenheimer)\n4. Ben Whishaw (American Fiction)\n5. Brad Pitt (Godzilla Minus One)\n6. Cillian Murphy (Poor Things)\n7. Colin Farrell (The Holdovers)\n8. Daniel Radcliffe (20 Days in Mariupol)\n9. Daveed Diggs (War Is Over!)\n10. Jake Gyllenhall (The Last Repair Shop)\n11. Joaquin Phoenix (The Wonderful Story of Henry Sugar)", "text": "<|system|>\nYou are an AI language model developed by IBM Research. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behavior.\n<|user|>\nWho was nominated for Best Actor but did not win at the Oscars this year?\n<|assistant|>\nThe nominees for Best Actor who did not win include:\n1. Adam Driver (The Zone of Interest)\n2. Antonio Banderas (Barbie)\n3. Austin Butler (Oppenheimer)\n4. Ben Whishaw (American Fiction)\n5. Brad Pitt (Godzilla Minus One)\n6. Cillian Murphy (Poor Things)\n7. Colin Farrell (The Holdovers)\n8. Daniel Radcliffe (20 Days in Mariupol)\n9. Daveed Diggs (War Is Over!)\n10. Jake Gyllenhall (The Last Repair Shop)\n11. Joaquin Phoenix (The Wonderful Story of Henry Sugar)<|endoftext|>"}'

Then asking that question I get the following response:

Jake Gyllenhall was one of the actors who was nominated for Best Actor but did not win at the 2024 Oscars. He received recognition for his   │
│ outstanding performance in "Love Again".

That is the a valid actor but for the wrong movie.

**Comment by chudegao** [comment]
Seems the generated data is fine. How many lines of your traininig data ( wc -l taxonomy_data/train_gen.jsonl  )?  What's the training parameters you used? (e.g. --iters, --skip-quantize).   Seems you use 4-bit quantize, it's performance maybe not good as expected. Try to use --skip-quantize True.  And make sure run enough iterations based on your data.

I'm on linux and use fp16, the result looks much better.

**Comment by stevef1uk** [comment]
> Seems the generated data is fine. How many lines of your traininig data ( wc -l taxonomy_data/train_gen.jsonl )? What's the training parameters you used? (e.g. --iters, --skip-quantize). Seems you use 4-bit quantize, it's performance maybe not good as expected. Try to use --skip-quantize True. And make sure run enough iterations based on your data.
> 
> I'm on linux and use fp16, the result looks much better.

100 lines

I just used the default parameters and Generation took 1953.81s & Training 44.59s .

I can try to increate the iterations as you suggested & apply that --skip-quantize flag. I report back when it finishes. I am not having to use that server today so I can leave it running for a while.

**Comment by stevef1uk** [comment]
I ran with 250 iteration & it took a long time. It finished overnight.

When I try to run 
```
ilab test
```

I am getting the following errors. 

File "/Users/stevef/dev/instructlab/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-666947b9-48ea49b25c2db85c7d72c70a;33d65ff9-77b3-4a86-9312-9131739e9cd7)

Repository Not Found for url: https://huggingface.co/api/models/instructlab-merlinite-7b-lab-mlx-q/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

I have correlated a HuggingFace token & logged on using the huggingface-cli so I am not sure what to do now?

**Comment by PaulaViguri** [comment]
I am facing exactly the same issue, the newly trained model is answering nonsense and performing way worse than the initial merlinite model. 
Trained model behaviour: 
![image](https://github.com/instructlab/instructlab/assets/104971777/034e50ea-76da-496f-9b91-01e3635879e9)
Initial model behaviour:
![image](https://github.com/instructlab/instructlab/assets/104971777/f5cc8596-80be-40de-9bde-6262aa842045)

**Comment by stevef1uk** [comment]
I know all the RedHatters are working on productising this project, however, I really feel it needs to work as advertised and currently it really doesn't seem to UNLESS we newbie early adopters are doing something wrong. The model I have tested had the --skip-de-quantize  set throughout.

**Comment by nathan-weinberg** [comment]
@stevef1uk are you hitting the same problem with `v0.17.0`?

**Comment by stevef1uk** [comment]
> @stevef1uk are you hitting the same problem with `v0.17.0`?

Sorry I haven't had a chance to try I was fairly successfully running Grant's Delores example, it takes a very long time to tun on my hardware.

**Comment by vincentywdeng** [comment]
I ran into same issue with the  finue tuned model trained by the generated data using same qna.yaml provided in  [README](https://github.com/instructlab/taxonomy).
```
version: 2
task_description: 'Teach the model the results of the 2024 Oscars'
created_by: juliadenham
domain: pop_culture
seed_examples:
 - question: When did the 2024 Oscars happen?
   answer: |
     The 2024 Oscars were held on March 10, 2024.
 - question: What film had the most Oscar nominations in 2024?
   answer: |
     Oppenheimer had 13 Oscar nominations.
 - question: Who presented the 2024 Oscar for Best Original Screenplay and Best Adapted Screenplay?
   answer: |
     Octavia Spencer presented the award for Best Original Screenplay and Best Adapted Screenplay at the 2024 Oscars.
 - question: Who hosted the 2024 Oscars?
   answer: |
     Jimmy Kimmel hosted the 96th Academy Awards ceremony.
 - question: At the 2024 Oscars, who were the nominees for best director and who won?
   answer: |
     The nominees for director at the 2024 Oscars was Christopher Nolan for Oppenheimer,
     Justine Triet for Anatomy of a Fall, Martin Scorsese for Killers of the Flower Moon,
     Yorgos Lanthimos for Poor Things, and Jonathan Glazer for The Zone of Interest.
     Christopher Nolan won best director for Oppenheimer.
 - question: Did Billie Eilish perform at the 2024 Oscars?
   answer: |
     Yes Billie Eilish performed "What Was I Made For?" from Barbie at the 2024 Oscars.
document:
 repo: https://github.com/juliadenham/oscars2024_knowledge.git
 commit: e1744af
 patterns:
   - oscars2024_results.md
```

I checked the generated training data `taxonomy_data/train_gen.jsonl` and find the generated testing data is WRONG for example
```
{"system": "You are an AI language model developed by IBM Research. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behavior.", "user": "Who won the award for Best Actress in a Leading Role at the Oscars in 2024?", "assistant": "Jessica Chastain won the award for Best Actress in a Leading Role at the 96th Academy Awards."}
```
I assume the `ilab generate` follows the document property in the qna.yaml to get the truth from  https://github.com/juliadenham/oscars2024_knowledge/blob/main/oscars2024_results.md to generate test data. However,  The truth document states the correct answer should be Emma Stone

I'm in 0.17.0 by the way.
