### ISSUE TITLE
`config.yaml` should provide default model location across commands

### ISSUE THREAD

**Issue by mairin** [instructlab/instructlab#1377]
I suspect config.yaml in offering very specific, different path possibilities for model locations on the host (generate, serve, chat) might offer too fine-grained a configuration. 

I have models on my system that I'd already downloaded in /srv/models.... I didn't realize there were three model paths in the config.yaml to start so I got a traceback when i tried `ilab serve` and it couldn't find the model in the default model path. 

Probably, under `general:` - have a path to a directory where models are stored that's more global, and just put the name of the model or the subpath in the individual commands' config.

Only sticky point is perhaps if you want a mix of local and remote models.... but then you could override the local model dir (which could be thusly named, local_model_dir) with a url to an endpoint in the individual commands' config areas. eg

```
general:
  local_model_dir: /srv/models
chat:
  model: 'Mistral AI'/mixtral-8x7b-instruct.gguf
generate:
  model: https://blahblah.endpoint/api:1234
```
