### ISSUE TITLE
Add comments to the config.yaml

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#1943]
Update the config.yaml generation code to inject comments describing the fields. The current config file does not explain what these fields do. We should update the logic to add more comments for clarity.

**Comment by alinaryan** [comment]
@cdoern is this a GA blocker?

**Comment by jaideepr97** [comment]
Is this kind of what we're looking for in the `config.yaml` after `ilab config init`?
```yaml
...
evaluate:
  base_branch: null
  # baseline model used to compare evaluation results against and detect regressions
  base_model: instructlab/granite-7b-lab
  branch: null
  # no. of GPUs to be used for running evaluations
  gpus: 1
  mmlu:
    batch_size: auto
    few_shots: 2
  # Settings to run MMLU against branch containing taxonomy additions
...
```
