### ISSUE TITLE
Add pdf check to ilab taxonomy diff 

### ISSUE THREAD

**Issue by aakankshaduggal** [instructlab/instructlab#2306]
Earlier we only supported markdown files as supported documents with `qna.yaml` files. But with the new [context-aware chunking feature](https://github.com/instructlab/sdg/issues/271) being included in SDG we would be able to add pdf contributions as well. 

What was acceptable before?

```
created_by: instructlab
domain: textbook
...
task_description: Teaching about human anatomy
document:
  repo: https://github.com/instructlab/reponame
  commit: 86b15e9c5701886850e8f85ad67cb56e049997c1
  patterns:
  - filename.md
  ```
  
  What will be acceptable now?
  
  ```
created_by: instructlab
domain: textbook
...
task_description: Teaching about human anatomy
document:
  repo: https://github.com/instructlab/reponame
  commit: 86b15e9c5701886850e8f85ad67cb56e049997c1
  patterns:
  - filename.pdf
  ```
  
  To address this new functionality with SDG, we need to update the `ilab taxonomy diff` validation criteria to also accept pdfs for the e2e to still pass with new SDG code changes.
