### ISSUE TITLE
Issues with multi model downloads

### ISSUE THREAD

**Issue by jaideepr97** [instructlab/instructlab#2490]
**Describe the bug**
Currently `ilab model download` supports specifying multiple repositories and filenames to be downloaded via `--repository` and `--filenames` 
however, 
- `--release` still only accepts a single value, forcing users to download the same version for all specified models whether it exists or not
- there is an assumption that users are either specifying all safetensor repos or all GGUF repos. If users were to try and specify a mix of repositories and also specify a list of filenames that don't match one-to-one with the repositories, the workflow breaks and models are not downloaded properly. Users also don't have a way to express which filenames should be mapped to which specified repository 

**To Reproduce**
1. run `ilab model download -repository instructlab/granite-7b-lab -repository instructlab/granite-7b-lab-GGUF -filename granite-7b-lab-Q4_K_M.gguf`
2. See download not proceeding as expected 

**Expected behavior**
All specified models are downloaded as expected 

**Screenshots**

**Device Info (please complete the following information):**
```
╰─ ilab system info                                                                                                                                                                        ─╯
Platform:
  sys.version: 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)]
  sys.platform: darwin
  os.name: posix
  platform.release: 24.0.0
  platform.machine: arm64
  platform.node: jrao-mac
  platform.python_version: 3.11.9
  platform.cpu_brand: Apple M3 Pro
  memory.total: 36.00 GB
  memory.available: 14.38 GB
  memory.used: 15.94 GB

InstructLab:
  instructlab.version: 0.19.0rc2.dev154
  instructlab-dolomite.version: 0.1.1
  instructlab-eval.version: 0.3.1
  instructlab-quantize.version: 0.1.0
  instructlab-schema.version: 0.4.1
  instructlab-sdg.version: 0.3.0
  instructlab-training.version: 0.5.2

Torch:
  torch.version: 2.3.1
  torch.backends.cpu.capability: NO AVX
  torch.version.cuda: None
  torch.version.hip: None
  torch.cuda.available: False
  torch.backends.cuda.is_built: False
  torch.backends.mps.is_built: True
  torch.backends.mps.is_available: True

llama_cpp_python:
  llama_cpp_python.version: 0.2.79
  llama_cpp_python.supports_gpu_offload: True
```

**Additional context**
