### ISSUE TITLE
Show os-release variant information in `ilab system info`

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#2720]
**Is your feature request related to a problem? Please describe.**
`/etc/os-release` can contain information about an OS variant. It would be useful to include the information in the output of `ilab system info`

**Describe the solution you'd like**
For `/etc/os-release` content

```
VARIANT="Some Product Name"
VARIANT_ID=product_name
PRODUCT_NAME_VERSION_ID=1.2.3
```

show

```
os-release.VARIANT: Some Product Name
os-release.PRODUCT_NAME_VERSION_ID: 1.2.3
```

`PRODUCT_NAME_VERSION_ID` is coming from upper-case `VARIANT_ID`.

**Comment by jaideepr97** [comment]
Thanks for raising this @tiran 
I agree this could be useful

**Comment by tiran** [comment]
It was Rom's idea. I'm just the messenger.

**Comment by reidliu41** [comment]
Checking it in fedora, looks like below, VARIANT_ID is not like 1.2.3, and `os-release.PRETTY_NAME` include `VARIANT`, not enough? Please correct if I misunderstanding..
```
VARIANT="Server Edition"
VARIANT_ID=server

# ilab system info
Platform:
  sys.version: 3.11.9 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)]
  sys.platform: linux
  os.name: posix
  platform.release: 6.8.5-301.fc40.x86_64
  platform.machine: x86_64
  platform.node: fedora153
  platform.python_version: 3.11.9
  os-release.ID: fedora
  os-release.VERSION_ID: 40
  os-release.PRETTY_NAME: Fedora Linux 40 (Server Edition)
  memory.total: 72.23 GB
  memory.available: 70.54 GB
  memory.used: 0.94 GB
```
and there is no VARIANT and VARIANT_ID in rhel
```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"


# ilab system info
Platform:
  sys.version: 3.11.7 (main, Jul  4 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
  sys.platform: linux
  os.name: posix
  platform.release: 5.14.0-284.11.1.el9_2.x86_64
  platform.machine: x86_64
  platform.node: rhel9u2-2
  platform.python_version: 3.11.7
  os-release.ID: rhel
  os-release.VERSION_ID: 9.2
  os-release.PRETTY_NAME: Red Hat Enterprise Linux 9.2 (Plow)
  memory.total: 62.62 GB
  memory.available: 61.50 GB
  memory.used: 0.46 GB
```
