### ISSUE TITLE
Bug: ilab model download fails to download Mixtral-8x7B-Instruct-v0.1 on L40S (Synthetic Data) by default

### ISSUE THREAD

**Issue by kami619** [instructlab/instructlab#3071]
**Describe the bug**
Nvidia L40S profile supports a Mixtral-8x7B-Instruct-v0.1 teacher model for synthetic data generation but it doesn't support the model download on `ilab model download` command.

**To Reproduce**
Setup the `HF_TOKEN` variable with your Hugging Face token, to be able to download models from hugging face repository.

1. ilab config init (use defaults for the L40S NVIDIA Profile) 
3. ilab model download (Downloads the default GGUF models)
4. ilab model serve (defaults)
5. ilab model chat (defaults, for initial exploration)
6. Do the work to build some new knowledge and qna.yaml.
7. ilab taxonomy diff
8. ilab data generate <-- this is where the defaults fail asking for a Mixtral model which is needed by the profile setup.

**Expected behavior**
From a Usability point of view, we would want the needed defaults for the data generation or training to download the required models on its own.

**Logs**

```
# ilab data generate
INFO 2025-01-30 11:30:21,787 instructlab.process.process:241: Started subprocess with PID 5222. Logs are being written to /root/.local/share/instructlab/logs/generation/generation-801ccea6-df27-11ef-a283-02001c7a353b.log.
/root/.cache/instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1 does not exist. Please download model first.
failed to generate data with exception: /root/.cache/instructlab/models/mistralai/Mixtral-8x7B-Instruct-v0.1 does not exist. Please download model first.
```

**Device Info (please complete the following information):**
 - Hardware Specs: IBM Cloud - gx3-24x120x1l40s
 - GPU: 1 x NVIDIA L40S 48 GB
 - OS Version: RHEL 9
 - Python Version: 3.11
 - InstructLab Version: 1.23.1

**Additional context**
Based on the discussion with @alimaredia the fix could be along the lines of.,

If someone were to fix this issue, they would need to 
  1. Add a repositories section to the download section of the config. 
  2. Change all of the system profiles to have the correct defaults. 
  3. Change the repositories flag.

Also the [guide](https://github.com/instructlab/instructlab/blob/main/docs/instructlab_models.md) associated with this is broken under the [Download the Model](https://github.com/instructlab/instructlab?tab=readme-ov-file#-download-the-model) section of the docs.

**Comment by dmartinol** [comment]
The guide states `You may be prompted to use your Hugging Face token to download the Mistral-7B-Instruct-v0.2-GGUF model.`, e.g.:
```
ilab model download --hf-token <your-huggingface-token>
```

**Comment by kami619** [comment]
@dmartinol thanks for looking at this, I should have mentioned in the bug (i will update it now) that I was setting the HF_TOKEN env variable when I run that command. But it only downloads., these models by default.

```
+--------------------------------------+---------------------+--------+
| Model Name                           | Last Modified       | Size   |
+--------------------------------------+---------------------+--------+
| merlinite-7b-lab-Q4_K_M.gguf         | 2024-12-20 12:09:24 | 4.1 GB |
| mistral-7b-instruct-v0.2.Q4_K_M.gguf | 2025-01-02 15:05:49 | 4.1 GB |
| granite-7b-lab-Q4_K_M.gguf           | 2024-12-20 12:07:47 | 3.8 GB |
+--------------------------------------+---------------------+--------+
```

**Comment by dmartinol** [comment]
You are right then: if you do not specify any argument, despite you initialized InstructLab using a device profile, the default command `ilab model download` doesn't take into account the profile. You must download them explicitly for now using the `--repository` option.

@cdoern Given the recent updates to the `clickext` module that allow to refer to values defined in different config sections, we could also take this as an opportunity to review how we espose the model paths in the configuration, as we mostly repeat the same values under different sections. 
E.g., in `default_config` I count 2 occurrences of `instructlab/granite-7b-lab` and 2 each of `prometheus-eval/prometheus-8x7b-v2.0` and `Mixtral-8x7B-Instruct-v0.1`.

Maybe a simpler config could be to put all of them in a single section like:
```yaml
models:
  - name: granite-7b
    repo: instructlab/granite-7b-lab-GGUF
    path: ...models/granite-7b-lab-Q4_K_M.gguf
  - name: embedding
    repo: ibm-granite/granite-embedding-125m-english
    path: ...models/ibm-granite/granite-embedding-125m-english
  - name: eval
    repo: prometheus-eval/prometheus-8x7b-v2.0
    path: .../models/prometheus-eval/prometheus-8x7b-v2.0
```
and let the default download command download all of them, no matter the number in the list?

In the command sections, we can then reference them with path reference like:
```yaml
generate:
  teacher:
    model_path: ref:/models/granite-7b
...
serve:
  model_path: ref:/models/granite-7b
...
train:
  phased_mt_bench_judge: ref:/models/eval
...
```

BTW: I just realized that by default we also download `instructlab/merlinite-7b-lab-GGUF` which instead is not in the default config. Is it really needed?
