### ISSUE TITLE
ilab model serve does not work with FIPS Mode enabled

### ISSUE THREAD

**Issue by AaronJaegerVA** [instructlab/instructlab#3237]
**Describe the bug**
`ilab model serve` fails on systems with FIPS Mode enabled.

**To Reproduce**
1. Run `ilab model serve` on a system with FIPS Mode enabled.

**Expected behavior**
Model is served successfully using vLLM.

**Screenshots**
```
ilab model serve
...
ERROR 03-19 17:10:32 [registry.py:331]   File "/opt/app-root/lib64/python3.11/site-packages/torch/utils/hipify/hipify_python.py", line 683, in __init__
ERROR 03-19 17:10:32 [registry.py:331]     self._hash = hashlib.md5()
ERROR 03-19 17:10:32 [registry.py:331]                  ^^^^^^^^^^^^^
ERROR 03-19 17:10:32 [registry.py:331] _hashlib.UnsupportedDigestmodError: [digital envelope routines] unsupported
ERROR 03-19 17:10:32 [registry.py:331]
...
ValueError: Model architectures ['GraniteForCausalLM'] failed to be inspected. Please check the logs for more details.
```

**Device Info (please complete the following information):**
 - Hardware Specs: 2CPU, 8GB RAM, NVIDIA T4 GPU
 - OS Version: RHEL 9.4
 - Python Version: Python 3.11.7
 - InstructLab Version: [output of `ilab system info`]

```
Platform:
  sys.version: 3.11.7 (main, Oct  9 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
  sys.platform: linux
  os.name: posix
  platform.release: 5.14.0-427.55.1.el9_4.x86_64
  platform.machine: x86_64
  platform.node: llm-test-0
  platform.python_version: 3.11.7
  os-release.ID: rhel
  os-release.VERSION_ID: 9.4
  os-release.PRETTY_NAME: Red Hat Enterprise Linux 9.4 (Plow)
  memory.total: 30.89 GB
  memory.available: 19.73 GB
  memory.used: 10.66 GB

InstructLab:
  instructlab.version: 0.24.3
  instructlab-dolomite.version: 0.2.0
  instructlab-eval.version: 0.5.1
  instructlab-quantize.version: 0.1.0
  instructlab-schema.version: 0.4.2
  instructlab-sdg.version: 0.7.2
  instructlab-training.version: 0.7.0

Torch:
  torch.version: 2.6.0+cu124
  torch.backends.cpu.capability: AVX512
  torch.version.cuda: 12.4
  torch.version.hip: None
  torch.cuda.available: True
  torch.backends.cuda.is_built: True
  torch.backends.mps.is_built: False
  torch.backends.mps.is_available: False
  torch.cuda.bf16: True
  torch.cuda.current.device: 0
  torch.cuda.0.name: Tesla T4
  torch.cuda.0.free: 14.5 GB
  torch.cuda.0.total: 14.6 GB
  torch.cuda.0.capability: 7.5 (see https://developer.nvidia.com/cuda-gpus#compute)

llama_cpp_python:
  llama_cpp_python.version: 0.3.6
  llama_cpp_python.supports_gpu_offload: False
```
