### ISSUE TITLE
ilab reports 'Provided path to model does not exist' when using accelerated training

### ISSUE THREAD

**Issue by shaneboulden** [instructlab/instructlab#3246]
**Describe the bug**
InstructLab reports that the provided path to the model does not exist when using an accelerated pipeline.

**To Reproduce**
1. Download the granite-7b-lab model:
```
HF_TOKEN=... ilab model download --repository instructlab/granite-7b-lab
```
2. Verify that the model is available:
```
ilab model list
+--------------------------------------+---------------------+---------+
| Model Name                           | Last Modified       | Size    |
+--------------------------------------+---------------------+---------+
| instructlab/granite-7b-lab           | 2025-03-26 21:20:49 | 12.6 GB |
| mistral-7b-instruct-v0.2.Q4_K_M.gguf | 2025-03-26 21:14:36 | 4.1 GB  |
| granite-7b-lab-Q4_K_M.gguf           | 2025-03-26 21:12:23 | 3.8 GB  |
| merlinite-7b-lab-Q4_K_M.gguf         | 2025-03-26 21:13:32 | 4.1 GB  |
+--------------------------------------+---------------------+---------+
```
Attempt to train a model:
```
ilab model train --device cuda --pipeline accelerated --data-path ~/.local/share/instructlab/datasets/2025-03-26_175846/skills_train_msgs_2025-03-26T17_58_59.jsonl --model-path instructlab/granite-7b-lab --optimize-memory --gpus 1
...
FileNotFoundError: Provided path to model does not exist. Please make sure that you've passed a valid model and that it has appropriate permissions: instructlab/granite-7b-lab
Message: 'Failed during training loop: '
Arguments: (FileNotFoundError("Provided path to model does not exist. Please make sure that you've passed a valid model and that it has appropriate permissions: instructlab/granite-7b-lab"),)
Accelerated Training failed with 1
```

**Expected behavior**
InstructLab trains the specified model.

**Device Info (please complete the following information):**
 - Hardware Specs: WSL, Ryzen 5800X3D, RTX 3070 with CUDA 12.6
 - OS Version:  Fedora 40 (on WSL)
 - Python Version: Python 3.11.10
 - InstructLab Version: [output of `ilab system info`]:
```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3070, compute capability 8.6, VMM: yes
Platform:
  sys.version: 3.11.10 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]
  sys.platform: linux
  os.name: posix
  platform.release: 5.15.167.4-microsoft-standard-WSL2
  platform.machine: x86_64
  platform.node: HelixWin
  platform.python_version: 3.11.10
  os-release.ID: fedora
  os-release.VERSION_ID: 40
  os-release.PRETTY_NAME: Fedora Linux 40 (Container Image)
  os-release.VARIANT: Container Image
  memory.total: 31.31 GB
  memory.available: 29.88 GB
  memory.used: 0.99 GB

InstructLab:
  instructlab.version: 0.23.5
  instructlab-dolomite.version: 0.2.0
  instructlab-eval.version: 0.5.1
  instructlab-quantize.version: 0.1.0
  instructlab-schema.version: 0.4.2
  instructlab-sdg.version: 0.7.2
  instructlab-training.version: 0.7.0

Torch:
  torch.version: 2.5.1+cu124
  torch.backends.cpu.capability: AVX2
  torch.version.cuda: 12.4
  torch.version.hip: None
  torch.cuda.available: True
  torch.backends.cuda.is_built: True
  torch.backends.mps.is_built: False
  torch.backends.mps.is_available: False
  torch.cuda.bf16: True
  torch.cuda.current.device: 0
  torch.cuda.0.name: NVIDIA GeForce RTX 3070
  torch.cuda.0.free: 6.9 GB
  torch.cuda.0.total: 8.0 GB
  torch.cuda.0.capability: 8.6 (see https://developer.nvidia.com/cuda-gpus#compute)

llama_cpp_python:
  llama_cpp_python.version: 0.3.2
  llama_cpp_python.supports_gpu_offload: True
```
