### ISSUE TITLE
`ilab config edit` fails when there's an error in the configuration

### ISSUE THREAD

**Issue by jannfis** [instructlab/instructlab#3260]
**Describe the bug**

When there's an error in the configuration, `ilab config edit` won't let you fix your mistake. 

It exits early with:

```
(rocm-venv) ilab config edit
Usage: ilab config [OPTIONS] COMMAND [ARGS]...
Try 'ilab config --help' for help.

Error: 1 errors in /root/.config/instructlab/config.yaml:
- string_pattern_mismatch serve->backend: string should match pattern 'vllm|llama-cpp'
```

I'm not sure if that holds true for every error in the configuration, but I set a wrong (unknown) backend and I won't be able to fix it unless I fire up an editor myself.

**To Reproduce**

* Set an invalid backend in `.serve.backend` or `.serve.server.bakcned`
* Try to run `ilab config edit` afterwards

**Expected behavior**

I was expecting `ilab config edit` to let me edit the configuration, despite there being an error.

**Screenshots**

**Device Info (please complete the following information):**
```
(rocm-venv) ilab system info
Platform:
  sys.version: 3.11.11 (main, Feb 10 2025, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
  sys.platform: linux
  os.name: posix
  platform.release: 6.13.9-200.fc41.x86_64
  platform.machine: x86_64
  platform.node: 3a34a80c25c2
  platform.python_version: 3.11.11
  os-release.ID: fedora
  os-release.VERSION_ID: 40
  os-release.PRETTY_NAME: Fedora Linux 40 (Toolbx Container Image)
  os-release.VARIANT: Toolbx Container Image
  memory.total: 125.55 GB
  memory.available: 111.88 GB
  memory.used: 11.14 GB

InstructLab:
  instructlab.version: 0.23.0rc1.dev249
  instructlab-dolomite.version: 0.2.0
  instructlab-eval.version: 0.5.1
  instructlab-quantize.version: 0.1.0
  instructlab-schema.version: 0.4.2
  instructlab-sdg.version: 0.7.3
  instructlab-training.version: 0.7.0

Torch:
  torch.version: 2.6.0+rocm6.1
  torch.backends.cpu.capability: AVX2
  torch.version.cuda: None
  torch.version.hip: 6.1.40091-a8dbc0c19
  torch.cuda.available: True
  torch.backends.cuda.is_built: True
  torch.backends.mps.is_built: False
  torch.backends.mps.is_available: False
  torch.cuda.bf16: True
  torch.cuda.current.device: 0
  torch.cuda.0.name: AMD Radeon RX 7800 XT
  torch.cuda.0.free: 15.8 GB
  torch.cuda.0.total: 16.0 GB
  torch.cuda.0.capability: 11.0 (see https://developer.nvidia.com/cuda-gpus#compute)

llama_cpp_python:
  llama_cpp_python.version: 0.3.6
  llama_cpp_python.supports_gpu_offload: False
```

**Additional context**
