### ISSUE TITLE
error when running lab generate - generate_data.py:538 'question'

### ISSUE THREAD

**Issue by ruchimahindru** [instructlab/instructlab#601]
lab generate
INFO 2024-03-13 16:53:45,619 lab.py:344 Generating model 'merlinite-7b-Q4_K_M' using 10 cpus, taxonomy: 'taxonomy' and seed 'seed_tasks.json' against http://localhost:8000/v1 server
INFO 2024-03-13 16:53:45,746 generate_data.py:563 Found new taxonomy files :
INFO 2024-03-13 16:53:45,746 generate_data.py:565 * compositional_skills/writing/grounded/summarization/case_summarization/question_generation/qna.yaml
<method-wrapper '__repr__' of KeyError object at 0x148d25840>  in  taxonomy/compositional_skills/writing/grounded/summarization/case_summarization/question_generation/qna.yaml
ERROR 2024-03-13 16:53:45,747 generate_data.py:538 'question'
1 taxonomy files with errors! Exiting.

Here's the sample qna.xml
```yaml
seed_examples:
- answer: How do I renew the Apple MDM certificate?
  context: "How do i renew the apple mdm certificate? I looked into it but not sure. Need help as this expires in 9 days"
- answer: How do I resend a Blueworks Live invitation link?
  context: "IBM Blueworks Live Account Activation Link is expired. A new one link is needed to access my organizations Blueworks site."
  question: Generate a concise summary question for the given text.
task_description: ''
```
