### ISSUE TITLE
Bug: Knowledge qna.yaml validation

### ISSUE THREAD

**Issue by anik120** [instructlab/instructlab#847]
```
created_by: test-bot
domain: test-domain
seed_examples:
.
.
.
task_description: For testing knowledge
document:
  repo: https://github.com/example-org/example-repo
  commit: a0c3c8e
  patterns:
  - *.md
```

For the pattern mentioned above, it throws the following error: 

```
ERROR 2024-04-10 16:23:07,593 utils.py:120 error found in file taxonomy/knowledge/textbook/puns-copy/general/qna.yaml: syntax error: expected alphabetic or numeric character, but found '.' (syntax) 11 None
Reading taxonomy failed with the following error: 1 taxonomy files with errors! Exiting.
```

If the pattern is changed to `something*.md` instead, it passes validation 

```
Taxonomy in /taxonomy/ is valid :)
```

`*.md` is a valid pattern and should be passing the validation check.
