### ISSUE TITLE
generating from knowledge doc can continue without any knowledge

### ISSUE THREAD

**Issue by derekhiggins** [instructlab/instructlab#901]
During synthetic instruction generation, the process continues if the pattern specified isn't found in the git repository

e.g. if there is a typo in the pattern here

```
document:
  repo: https://github.com/org/repo/
  commit: 558859d488075a08032ac9adb022d425f05a0723
  patterns:
  - README.typo

```

The prompt gets sent to the server without any document, as a result synthetic instructions are generated with no relevance
to the knowleged (they get some context from the manual instructions)
