### ISSUE TITLE
Error handling for missing .md files

### ISSUE THREAD

**Issue by aartij22** [instructlab/instructlab#903]
If user enters the below pattern, `ilab diff` returns valid.

```
document:
  repo: https://github.com/aartij22/doc_test.git
  commit: 272875d
  patterns:
    - 'README.txt'
 ```

Raise an error if no markdown (.md) files are found. Currently, the code doesn't warn users and continues with `ilab generate`.
