### ISSUE TITLE
Unable to train instructlab/granite-7b-lab-GGUF model

### ISSUE THREAD

**Issue by skairali** [instructlab/instructlab#967]
We are able to download the granite model using below command

ilab download --repository instructlab/granite-7b-lab-GGUF --release main --filename granite-7b-lab-Q4_K_M.gguf
ilab generate is working fine

However ilab train is not able detec the MODEL TYPE properly and it thinks that its MISTRAL and training for merlinite and not granite

```
(venv) sudheesh@Sudheeshs-MacBook-Pro granite-lab % ilab train --iters 100 --gguf-model-path models/granite-7b-lab-Q4_K_M.gguf
[INFO] Loading
Fetching 11 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 12.84it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
dtype=mlx.core.float16
[INFO] Quantizing
Using model_type='mistral'
Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1244.079M
Trainable parameters 1.704M
Loading datasets
@oscar.urena.sequera 
```

We have updated config.yaml as follows. Which does not have any affect (works well for generate but dont see any affect on train)

```
chat:
  context: default
  greedy_mode: false
  logs_dir: data/chatlogs
  model: granite-7b-lab-Q4_K_M
  model_type: llama
  session: null
  vi_mode: false
  visible_overflow: true
general:
  log_level: INFO
generate:
  chunk_word_count: 1000
  model: granite-7b-lab-Q4_K_M
  model_type: llama
  num_cpus: 10
  num_instructions: 100
  output_dir: generated
  prompt_file: prompt.txt
  seed_file: seed_tasks.json
  taxonomy_base: origin/main
  taxonomy_path: taxonomy
serve:
  gpu_layers: -1
  host_port: 127.0.0.1:8000
  max_ctx_size: 4096
  model_path: models/granite-7b-lab-Q4_K_M.gguf
```

```

(venv) sudheesh@Sudheeshs-MacBook-Pro granite-lab % ilab --version
ilab, version 0.13.1

```

Please note that it works fine with mistral models
